[package]
name = "pathfinder-storage"
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
base64 = { workspace = true }
bincode = "2.0.0-rc.3"
bitvec = { workspace = true }
bloomfilter = "1.0.12"
cached = { workspace = true }
const_format = { workspace = true }
data-encoding = "2.4.0"
fake = { workspace = true }
hex = { workspace = true }
lazy_static = { workspace = true }
pathfinder-common = { path = "../common" }
pathfinder-crypto = { path = "../crypto" }
pathfinder-ethereum = { path = "../ethereum" }
pathfinder-serde = { path = "../serde" }
primitive-types = { workspace = true }
r2d2 = "0.8.10"
r2d2_sqlite = "0.21.0"
rand = { workspace = true }
rusqlite = { version = "0.28.0", features = ["bundled", "functions"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = [
    "arbitrary_precision",
    "raw_value",
] }
serde_with = { workspace = true }
sha3 = { workspace = true }
starknet-gateway-types = { path = "../gateway-types" }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
zstd = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
rstest = { workspace = true }
tempfile = "3.6"
test-log = { workspace = true }
tracing-subscriber = { workspace = true }
