[package]
name = "pathfinder-rpc"
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true, features = ["ws", "headers"] }
base64 = { workspace = true }
cached = { workspace = true }
flate2 = { workspace = true }
futures = { workspace = true }
http = { workspace = true }
hyper = "0.14.27"
metrics = { workspace = true }
mime = "0.3"
pathfinder-common = { path = "../common" }
pathfinder-compiler = { path = "../compiler" }
pathfinder-crypto = { path = "../crypto" }
pathfinder-ethereum = { path = "../ethereum" }
pathfinder-executor = { path = "../executor" }
pathfinder-merkle-tree = { path = "../merkle-tree" }
pathfinder-serde = { path = "../serde" }
pathfinder-storage = { path = "../storage" }
primitive-types = { workspace = true, features = ["serde"] }
reqwest = { workspace = true }
semver = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = [
    "arbitrary_precision",
    "raw_value",
] }
serde_with = { workspace = true }
starknet-gateway-client = { path = "../gateway-client" }
starknet-gateway-test-fixtures = { path = "../gateway-test-fixtures" }
starknet-gateway-types = { path = "../gateway-types" }
starknet_api = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["test-util", "process"] }
tower = { version = "0.4.13", default-features = false, features = [
    "filter",
    "util",
    "limit",
    "timeout",
] }
tower-http = { version = "0.4.0", default-features = false, features = [
    "cors",
    "limit",
    "request-id",
    "trace",
    "util",
] }
tracing = { workspace = true }
zstd = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
bytes = { workspace = true }
flate2 = { workspace = true }
hex = { workspace = true }
lazy_static = { workspace = true }
pathfinder-crypto = { path = "../crypto" }
pretty_assertions_sorted = { workspace = true }
rstest = { workspace = true }
tempfile = "3.6"
test-log = { workspace = true }
tokio-tungstenite = "0.20"
tracing-subscriber = { workspace = true }
